StoreFront.UI.MVC/Controllers/ProductCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class ProductCategoriesController : Controller
    {
        private PickleBall_StoreEntities db = new PickleBall_StoreEntities();

        // GET: ProductCategories
        public ActionResult Index()
        {
            return View(db.ProductCategories.ToList());
        }

        // GET: ProductCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // GET: ProductCategories/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ProductCategoryID,ProductCategory1")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.ProductCategories.Add(productCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productCategory);
        }

        // GET: ProductCategories/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductCategoryID,ProductCategory1")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productCategory);
        }

        // GET: ProductCategories/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategories/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategory productCategory = db.ProductCategories.Find(id);
            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using MVC3.UI.MVC.Utilities;
using System.Drawing;
using PagedList;
using PagedList.Mvc;
using StoreFront.UI.MVC.Models;

namespace StoreFront.UI.MVC.Controllers
{
    public class ProductsController : Controller
    {
        private PickleBall_StoreEntities db = new PickleBall_StoreEntities();

        // GET: Products
        public ActionResult Index(string searchFilter)
        {
            var products = db.Products.Include(p => p.ProductCategory).Include(p => p.ProductStatu);
            #region Optional Search filter

            if (String.IsNullOrEmpty(searchFilter))
            {
                var prod = db.Products;
                return View(prod.ToList());
            }
            else
            {

                string searchUpCase = searchFilter.ToUpper();

                List<Product> searchResults = db.Products.Where(
                    a => a.ProductName.ToUpper().Contains(searchUpCase)).ToList();

                return View(searchResults);
            }
            #endregion        
        }

       
        public ActionResult ProductsByCategory(string id)
        {
            var pbc = db.Products.Where(p => p.ProductCategory.ProductCategory1 == id);

            return View(pbc);
        }
       

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        #region Custom-add_to cart funtinality

        public ActionResult AddToCart(int qty, int productID)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            if (Session["cart"] != null)
            {
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            }
            else
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }

            Product product = db.Products.Where(p => p.ProductID == productID).FirstOrDefault();

            if (product == null)
            {
                return RedirectToAction("Index");
            }
            else
	        {
                CartItemViewModel item = new CartItemViewModel(qty, product);

                if (shoppingCart.ContainsKey(product.ProductID))
                {
                    shoppingCart[product.ProductID].Qty += qty;
                }
                else
                {
                    shoppingCart.Add(product.ProductID, item);
                }

                Session["cart"] = shoppingCart;
            }

            return RedirectToAction("Index", "ShoppingCart");
        }

        #endregion

        // GET: Products/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "ProductCategory1");
            ViewBag.ProductStatusID = new SelectList(db.ProductStatus, "ProductStatusID", "ProductStatusName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,ProductDesc,ProductStatusID,ProductCategoryID")] Product product, HttpPostedFileBase productPic)
        {
            if (ModelState.IsValid)       
            {
                #region File Upload

                string file = "NoImage.png";

                if (productPic != null)
                {
                    file = productPic.FileName;

                    string ext = file.Substring(file.LastIndexOf('.'));

                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".jif" };

                    if (goodExts.Contains(ext.ToLower()) && productPic.ContentLength <= 4194304)
                    {
                        file = Guid.NewGuid() + ext;

                        #region Resize Image

                        string savePath = Server.MapPath("~/Content/store_images/");

                        Image convertedImage = Image.FromStream(productPic.InputStream);

                        int maxImageSize = 500;

                        int maxThumbSize = 100;

                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                        #endregion
                    }

                    product.ProductImage = file;
                }

                #endregion

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "ProductCategory1", product.ProductCategoryID);
            ViewBag.ProductStatusID = new SelectList(db.ProductStatus, "ProductStatusID", "ProductStatusName", product.ProductStatusID);
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "ProductCategory1", product.ProductCategoryID);
            ViewBag.ProductStatusID = new SelectList(db.ProductStatus, "ProductStatusID", "ProductStatusName", product.ProductStatusID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,ProductDesc,ProductStatusID,ProductCategoryID")] Product product, HttpPostedFileBase productPic)
        {
            #region File Upload

            string file = "NoImage.png";

            if (productPic != null)
            {
                file = productPic.FileName;

                string ext = file.Substring(file.LastIndexOf('.'));

                string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                if (goodExts.Contains(ext.ToLower()) && productPic.ContentLength <= 4194304)
                {
                    file = Guid.NewGuid() + ext;

                    #region Resize Image

                    string savePath = Server.MapPath("~/Content/store_images/");

                    Image convertedImage = Image.FromStream(productPic.InputStream);

                    int maxImageSize = 500;

                    int maxThumbSize = 100;

                    ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                    #endregion

                    if (product.ProductImage != null && product.ProductImage != "NoImage.png")
                    {
                        string path = Server.MapPath("/Content/store_images/");
                        ImageUtility.Delete(path, product.ProductImage);
                    }

                    product.ProductImage = file;
                }
            }

            #endregion

            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "ProductCategory1", product.ProductCategoryID);
            ViewBag.ProductStatusID = new SelectList(db.ProductStatus, "ProductStatusID", "ProductStatusName", product.ProductStatusID);
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);

            string path = Server.MapPath("~/Content/store_images/");
            ImageUtility.Delete(path, product.ProductImage);

            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Views/Products/Create.cshtml
@model StoreFront.DATA.EF.Product

@{
    ViewBag.Title = "Add New Product";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6 text-are">
                @Html.EditorFor(model => model.ProductDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDesc, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductStatusID, "ProductStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6">
                @Html.DropDownList("ProductStatusID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductStatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCategoryID, "ProductCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6">
                @Html.DropDownList("ProductCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6">
               <input type="file" name="productPic" />
            </div>
        </div>
        @if (User.IsInRole("Admin"))
        {
        <div class="form-group">
            <div class="col-md-offset-2 col-lg-6">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
        }
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/Products/Delete.cshtml
@model StoreFront.DATA.EF.Product

@{
    ViewBag.Title = Model.ProductName + " - Delete";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to <u><b>permenantly</b></u> delete <u><b>@Model.ProductName</b></u>?</h3>
<div>
   
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductCategory.ProductCategory1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCategory.ProductCategory1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductStatu.ProductStatusName)
        </dt>

        @*<dd>
            @Html.DisplayFor(model => model.ProductStatu.ProductStatusName)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @if (User.IsInRole("Admin"))
        {
            <input type="submit" value="Delete" class="btn btn-default" />
        }
        | @Html.ActionLink("Back to List", "Index")
    </div>
    }
</div>

StoreFront.UI.MVC/Views/Products/Details.cshtml
@model StoreFront.DATA.EF.Product

@{
    ViewBag.Title = Model.ProductName + " - Details";
}

<h2>@ViewBag.Title</h2>

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductCategory.ProductCategory1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCategory.ProductCategory1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductStatu.ProductStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductStatu.ProductStatusName)
        </dd>    

    </dl>

    @* ADDED THIS FOR "ADD TO CART" FUNCTIONALITY *@
    <p>
        @using (Html.BeginForm("AddToCart", "Products", new { @productID = Model.ProductID }, FormMethod.Post, new { @class = "text-center" }))
        {
            @Html.HiddenFor(x => x.ProductID)
            <span class="label" style="color: #000">Quantity: </span>
            @Html.TextBox("Qty", 1, new { @class = "form-control", @style = "max-width: 50px; display : inline;" })
            <input type="submit" value="Add to Cart" class="btn btn-primary" name="qty" />
        }
    </p>
</div>
<div class="col-md-6">
    <img src="~/Content/store_images/@Model.ProductImage" alt="Book cover" title="@Model.ProductName" />
</div>
<div>
    @*@if (User.IsInRole("Admin"))
        {
            <div>
                @Html.ActionLink("Edit", "Edit", new { id = Model.ProductID })  |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
        else
        {*@
    @Html.ActionLink("Back to List", "Index")
    @* } *@

</div>

StoreFront.UI.MVC/Views/Products/Edit.cshtml
@model StoreFront.DATA.EF.Product

@{
    ViewBag.Title = "Edit - " + Model.ProductName;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProductID)

<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-lg-6">
            @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductDesc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-lg-6">
            @Html.EditorFor(model => model.ProductDesc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductDesc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-lg-6">
            @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductStatusID, "ProductStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-lg-6">
            @Html.DropDownList("ProductStatusID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductStatusID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductCategoryID, "ProductCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-lg-6">
            @Html.DropDownList("ProductCategoryID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductCategoryID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-lg-6">
           <img src="~/Content/store_images/@Model.ProductImage" alt="@Model.ProductName" style="max-width: 100px" />
           <hr />
            <input type="file" name="productPic" />
        </div>
    </div>
    @if (User.IsInRole("Admin"))
    {
    <div class="form-group">
        <div class="col-md-offset-2 col-lg-6">
            <input type="submit" value="Edit Product" class="btn btn-default" />
        </div>
    </div>
    }
</div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/Products/Index.cshtml
@model IEnumerable<StoreFront.DATA.EF.Product>
@*@using PagedList.Mvc;*@
@{
    ViewBag.Title = "Products";
}

<h2>@ViewBag.Title</h2>

@*@using (Html.BeginForm("Index", "Products", FormMethod.Get))
    {
        <p>
            Find by Product Name:
            @Html.TextBox("SearchString", ViewBag.SearchString as string)
            <input type="submit" value="Search" />
        </p>
    }

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchString = ViewBag.SearchString }))*@



@if (User.IsInRole("Admin"))
{
    <p>
        <div class="btn btn-light">@Html.ActionLink("Add New Product", "Create")</div>
        <div class="btn btn-light">@Html.ActionLink("Product Categories", "Index", "ProductCategories")</div>
    </p>
}


<table class="table data-table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductCategory.ProductCategory1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductStatu.ProductStatusName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductImage)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductCategory.ProductCategory1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductStatu.ProductStatusName)
                </td>
                <td>
                    <img src="~/Content/store_images/t_@item.ProductImage" alt="@item.ProductName" title="@item.ProductName" />
                </td>


                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ProductID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ProductID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ProductID })
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.ProductID })
                    </td>
                }
            </tr>
        }
    </tbody>

</table>

@section Scripts{
    <script>
        $(document).ready(function () {
            $(".data-table").DataTable();
        })
    </script>
}

StoreFront.UI.MVC/Views/Products/ProductsByCategory.cshtml
@model IEnumerable<StoreFront.DATA.EF.Product>

@{
    ViewBag.Title = "Products";
}

<h2>@ViewBag.Title</h2>
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Add New Product", "Create")
    </p>
}
<table class="table data-table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductCategory.ProductCategory1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductStatu.ProductStatusName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductImage)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductCategory.ProductCategory1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductStatu.ProductStatusName)
        </td>
        <td>
            <img src="~/Content/store_images/t_@item.ProductImage" alt="@item.ProductName" title="@item.ProductName" />

            @if (User.IsInRole("Admin"))
            {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ProductID })
                | @Html.ActionLink("Delete", "Delete", new { id = item.ProductID })
            </td>
        }
        else
        {
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ProductID })
            </td>
        }
        </tr>
    }

</table>

@section Scripts{
    <script>
        $(document).ready(function () {
            $(".data-table").DataTable();
        })
    </script>
}